development: &base
  adapter: postgresql
  database: botanicmap_development
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: botanicmap
  password: botanicmap
# Do not set this db to the same as development or production.
test:
  <<: *base

production:
  <<: *base
  database: botanicmap_production
  username: plantner
  password: plantner